### PR TITLE
Tolerate missing leading slash for 3 part names

### LINKED ISSUE #27: action invoke requires leading slash on packaged action
```
> nim action invoke whisk-system/utils/context   
 ›   Error: failed to invoke the action: the requested resource does not exist. (404 Not Found)
```

but this works:
```
> nim action invoke /whisk-system/utils/context  
{...}
```

### PR DESCRIPTION
**Pull request by rabbah**
## Description

Closes #27.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rabbah** [comment]
@jthomas @joshuaauerbachwatson gentle ping.

**Comment by jthomas** [comment]
LGTM - we should make the unit tests run under the CI/CD :)

**Comment by rabbah** [comment]
hmm why didn't GHA run :/ I did enable them. Thanks for pointing this out.

**Comment by rabbah** [comment]
https://github.com/nimbella/aio-cli-plugin-runtime/commit/4ff186be4d75893877e1f5147ab624d04d8cd5fe enabled GHA but I only enabled it on `dev` not on PRs.

**Comment by rabbah** [comment]
Closed by 0e1f6c6ecc768b1ef1c6362651a85032511ec22d.

**Pull request closed without merging**
