### PR TITLE
Bump aio lib version.

### PR DESCRIPTION
**Pull request by rabbah**
## Description

This picks up a couple of bug fixes related activation log stripping.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rabbah** [comment]
Looks like there's a formatting change where lists how have a separator.
```
     Datetime        Status   Kind      Version    Activation ID Start Wait Init Duration Entity
     ─────────────── ──────── ───────── ──────── ─ ───────────── ───── ──── ──── ──────── ──────
     05/22 06:39:38  success  nodejs:10 0.0.1    ◡ 12345         warm  --   0    23ms     foo···
```

**Comment by rabbah** [comment]
I am neutral on the separator - keep or drop? @jthomas @bhageena thoughts?

**Comment by jthomas** [comment]
I have no preferences either.... I'd happily pull anything new to keep up in sync with upstream if it comes to it.

**Comment by rabbah** [comment]
@bhageena may have to revert this. The tests failed due to the header change which may also affect the wb.

**Comment by rabbah** [comment]
@bhageena may have to revert this. The tests failed due to the header change which may also affect the wb.

**Comment by bhageena** [comment]
sure, doing it. needed some changes to be pulled in order to fix a wb issue. Will add the fix separately.

**Pull request merged**
